In [1]:
#https://towardsdatascience.com/cross-entropy-negative-log-likelihood-and-all-that-jazz-47a95bd2e81

import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
import torch

torch.manual_seed(0)

# Binary setting ##############################################################
print(f"{'Setting up binary case':-^80}")
z = torch.tensor([0.64, 0.27, 0.04, 0.02, 0.81])
yhat = torch.sigmoid(z)
#yhat = z
y = torch.Tensor([1,0,0,1,0])

print(f"{z=}\n{yhat=}\n{y=}\n{'':-^80}")
print("yhat.log(): ", yhat.log())
print("(1 - yhat).log()): ",(1 - yhat).log())
# First compute the negative log likelihoods using the derived formula
print("y * yhat.log(): ",y * yhat.log())
print("(1 - y) * (1 - yhat).log(): ",(1 - y) * (1 - yhat).log())

l = -(y * yhat.log() + (1 - y) * (1 - yhat).log())
print(f"{l}")

-----------------------------Setting up binary case-----------------------------
z=tensor([0.6400, 0.2700, 0.0400, 0.0200, 0.8100])
yhat=tensor([0.6548, 0.5671, 0.5100, 0.5050, 0.6921])
y=tensor([1., 0., 0., 1., 0.])
--------------------------------------------------------------------------------
yhat.log():  tensor([-0.4235, -0.5672, -0.6733, -0.6832, -0.3680])
(1 - yhat).log()):  tensor([-1.0635, -0.8372, -0.7133, -0.7032, -1.1780])
y * yhat.log():  tensor([-0.4235, -0.0000, -0.0000, -0.6832, -0.0000])
(1 - y) * (1 - yhat).log():  tensor([-0.0000, -0.8372, -0.7133, -0.0000, -1.1780])
tensor([0.4235, 0.8372, 0.7133, 0.6832, 1.1780])


In [13]:
# Observe that BCELoss and BCEWithLogitsLoss can produce the same results

# Supposing: z: prediction , s: sigmoid(z) , 
l_BCELoss_nored = torch.nn.BCELoss(reduction="none")(yhat, y) # log(s)
l_BCEWithLogitsLoss_nored = torch.nn.BCEWithLogitsLoss(reduction="none")(z, y) # log(z)
print(f"{l_BCELoss_nored}\n{l_BCEWithLogitsLoss_nored}\n{'':=^80}")

tensor([0.4235, 0.8372, 0.7133, 0.6832, 1.1780])
tensor([0.4235, 0.8372, 0.7133, 0.6832, 1.1780])


In [ ]:
import torch

torch.manual_seed(0)

# Binary setting ##############################################################
print(f"{'Setting up binary case':-^80}")
z = torch.randn(5)
yhat = torch.sigmoid(z)
y = torch.Tensor([0, 1, 1, 0, 1])
print(f"{z=}\n{yhat=}\n{y=}\n{'':-^80}")

# First compute the negative log likelihoods using the derived formula
l = -(y * yhat.log() + (1 - y) * (1 - yhat).log())
print(f"{l}")

# Observe that BCELoss and BCEWithLogitsLoss can produce the same results
l_BCELoss_nored = torch.nn.BCELoss(reduction="none")(yhat, y)
l_BCEWithLogitsLoss_nored = torch.nn.BCEWithLogitsLoss(reduction="none")(z, y)
print(f"{l_BCELoss_nored}\n{l_BCEWithLogitsLoss_nored}\n{'':=^80}")

# Multiclass setting ##########################################################
print(f"{'Setting up multiclass case':-^80}")
z2 = torch.randn(5, 3)
yhat2 = torch.softmax(z2, dim=-1)
y2 = torch.Tensor([0, 2, 1, 1, 0]).long()
print(f"{z2=}\n{yhat2=}\n{y2=}\n{'':-^80}")

# First compute the negative log likelihoods using the derived formulat
l2 = -yhat2.log()[torch.arange(5), y2]  # masking the correct entries
print(f"{l2}")
print(-torch.log_softmax(z2, dim=-1)[torch.arange(5), y2])

# Observe that NLLLoss and CrossEntropyLoss can produce the same results
l2_NLLLoss_nored = torch.nn.NLLLoss(reduction="none")(yhat2.log(), y2)
l2_CrossEntropyLoss_nored = torch.nn.CrossEntropyLoss(reduction="none")(z2, y2)
print(f"{l2_NLLLoss_nored}\n{l2_CrossEntropyLoss_nored}\n{'':=^80}")