In [2]:
# In remote: tensorboard --logdir=runs
# or: tensorboard dev upload --logdir runs \
#--name "My latest experiment" \ # optional
#--description "Simple comparison of several hyperparameters" # optional
# In local: ssh -L 6006:localhost:6006 tzq@192.168.30.46
# https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html

import torch
from torch.utils.tensorboard import SummaryWriter


In [3]:
# imports
import matplotlib.pyplot as plt
import numpy as np

import torch
import torchvision
import torchvision.transforms as transforms

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [4]:
writer = SummaryWriter()

In [8]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.lstm1 = nn.LSTM(1, 1, 1)

    def forward(self, x,h0,c0):
        output, (hn, cn) = self.lstm1(x,(h0,c0))
        return output,(hn, cn)

In [15]:
X = torch.rand(1,1,1)
net=NeuralNetwork()
h0 = torch.randn(1,1,1)
c0 = torch.randn(1,1,1)
pred,(hn,cn) = net(X,h0,c0)
print(pred)
print(hn)
print(cn)

tensor([[[-0.1633]]], grad_fn=<StackBackward>)
tensor([[[-0.1633]]], grad_fn=<StackBackward>)
tensor([[[-0.3745]]], grad_fn=<StackBackward>)


In [19]:
writer.add_graph(net,[X,h0,c0])