In [79]:
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('1Using {} device'.format(device))

1Using cuda device


In [80]:
rnn = nn.LSTM(1, 1, 1)
input = torch.randn(1,1,1)
h0 = torch.randn(1,1,1)
c0 = torch.randn(1,1,1)
output, (hn, cn) = rnn(input, (h0, c0))

In [81]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.lstm1 = nn.LSTM(1, 1, 1)

    def forward(self, x,h0,c0):
        output, (hn, cn) = self.lstm1(x,(h0,c0))
        return output,(hn, cn)

In [82]:
model = NeuralNetwork().to(device)

In [83]:
X = torch.rand(1,1,1, device=device)
h0 = torch.randn(1,1,1, device=device)
c0 = torch.randn(1,1,1, device=device)
print(model(X,h0,c0))

(tensor([[[-0.3122]]], device='cuda:0', grad_fn=<CudnnRnnBackward>), (tensor([[[-0.3122]]], device='cuda:0', grad_fn=<CudnnRnnBackward>), tensor([[[-0.6585]]], device='cuda:0', grad_fn=<CudnnRnnBackward>)))


In [102]:
# optimize 
learning_rate = 1e-2
batch_size = 64
epochs = 5

# Initialize the loss function
#loss_fn = nn.CrossEntropyLoss()
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [103]:
pred,(hn,cn) = model(X,h0,c0)
print(pred)
print(hn)
print(cn)

tensor([[[0.3947]]], device='cuda:0', grad_fn=<CudnnRnnBackward>)
tensor([[[0.3947]]], device='cuda:0', grad_fn=<CudnnRnnBackward>)
tensor([[[0.5311]]], device='cuda:0', grad_fn=<CudnnRnnBackward>)


In [106]:
dataloop = 50000
h0 = torch.randn(1,1,1, device=device)*0.0
c0 = torch.randn(1,1,1, device=device)*0.0
#output, (hn, cn) = rnn(input, (h0, c0))
def train_loop( model, loss_fn, optimizer,h0,c0):
    for i in range(dataloop):     
        X = torch.randn(1,1,1,device=device)
        y = torch.randn(1,1,1,device=device)
        y=y*0+0.1
        pred,(hn,cn) = model(X,h0,c0)

        loss = loss_fn(pred, y)
        
        # Backpropagation
        optimizer.zero_grad()
        torch.autograd.set_detect_anomaly(True)
        loss.backward(retain_graph=True)
        optimizer.step()
        h0 = hn.detach().clone()
        c0=cn.detach().clone()
        if i % 1000 == 0:
            loss = loss.item()
            print(f"loss: {loss:>7f} ")

In [108]:
h0 = torch.randn(1,1,1,device=device)*0
c0 = torch.randn(1,1,1,device=device)*0

for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(model, loss_fn, optimizer,h0,c0)

Epoch 1
-------------------------------
loss: 0.001769 
loss: 0.000000 
loss: 0.000004 
loss: 0.000009 
loss: 0.000003 
loss: 0.000002 
loss: 0.000000 
loss: 0.000007 
loss: 0.000023 
loss: 0.000008 
loss: 0.000000 
loss: 0.000001 
loss: 0.000010 
loss: 0.000000 
loss: 0.000020 
loss: 0.000019 
loss: 0.000000 
loss: 0.000015 
loss: 0.000009 
loss: 0.000000 
loss: 0.000032 
loss: 0.000000 
loss: 0.000001 
loss: 0.000000 
loss: 0.000001 
loss: 0.000001 
loss: 0.000015 
loss: 0.000017 
loss: 0.000005 
loss: 0.000000 
loss: 0.000001 
loss: 0.000001 
loss: 0.000003 
loss: 0.000005 
loss: 0.000004 
loss: 0.000005 
loss: 0.000000 
loss: 0.000002 
loss: 0.000003 
loss: 0.000001 
loss: 0.000000 
loss: 0.000003 
loss: 0.000005 
loss: 0.000024 
loss: 0.000000 
loss: 0.000001 
loss: 0.000013 
loss: 0.000001 
loss: 0.000000 
loss: 0.000000 
Epoch 2
-------------------------------
loss: 0.003605 
loss: 0.000006 
loss: 0.000001 
loss: 0.000009 
loss: 0.000000 
loss: 0.000001 
loss: 0.000011 
loss: 0.